# Generated by Django 6.0.4 on 2026-05-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Mois',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40, unique=True)),
                ('ordre', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Mois',
                'verbose_name_plural': 'Mois',
                'ordering': ['ordre', 'nom'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ordre__gte', 1), ('ordre__lte', 12)), name='mois_ordre_entre_1_et_12')],
            },
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(upload_to='cours_pdfs/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='cours.categorie')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='cours.mois')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
                'ordering': ['-cree_le'],
            },
        ),
    ]
