# Generated by Django 6.0.4 on 2026-05-10 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_abonnement', models.DateTimeField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='cours.categorie')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='cours.mois')),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
                'ordering': ['-date_abonnement'],
                'constraints': [models.UniqueConstraint(fields=('candidat', 'categorie', 'mois'), name='abonnement_unique_candidat_categorie_mois')],
            },
        ),
    ]
