# Generated by Django 6.0.4 on 2026-05-11 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_abonnement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('mensuel', 'Mensuel'), ('annuel', 'Annuel')], max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Option d'abonnement",
                'verbose_name_plural': "Options d'abonnement",
                'ordering': ['type_abonnement'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='abonnement',
            name='abonnement_unique_candidat_categorie_mois',
        ),
        migrations.AddField(
            model_name='abonnement',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Valide'), ('rejete', 'Rejete')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='abonnement',
            name='mois',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='cours.mois'),
        ),
        migrations.AddField(
            model_name='abonnement',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='abonnements', to='cours.optionabonnement'),
        ),
        migrations.AddConstraint(
            model_name='abonnement',
            constraint=models.UniqueConstraint(fields=('candidat', 'categorie', 'mois', 'option'), name='abonnement_unique_candidat_categorie_mois_option'),
        ),
    ]
