# Generated by Django 6.0.5 on 2026-05-12 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_optionabonnement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fichier_pdf', models.FileField(upload_to='corrections_pdfs/')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('mis_a_jour_le', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='cours.categorie')),
                ('mois', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='cours.mois')),
            ],
            options={
                'verbose_name': 'Correction',
                'verbose_name_plural': 'Corrections',
                'ordering': ['-cree_le'],
            },
        ),
    ]
