# Generated by Django 6.0.4 on 2026-05-12 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0004_correction'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionQuizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField(default=1)),
                ('question', models.TextField()),
                ('bonne_reponse', models.TextField()),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_items', to='cours.correction')),
            ],
            options={
                'verbose_name': 'Question de quiz (correction)',
                'verbose_name_plural': 'Questions de quiz (corrections)',
                'ordering': ['ordre', 'id'],
                'constraints': [models.UniqueConstraint(fields=('correction', 'ordre'), name='correction_quiz_item_unique_ordre')],
            },
        ),
    ]
